### ISSUE TITLE
RES, expandoes and NSFW posts

### ISSUE THREAD

**Issue by FaultLiner** [QTheme/Mindashq.Reddit.Theme#48]
With RES update, NSFW expandoes don't work because they use the :before element as the new "nsfw in expando" tag does. I've first noticed this in a sub I mod, but it isn't caused by my modifications, but by Mindashq code. I think swapping :before tags with :after tags should work.

(from a post at /r/Mindashq that didn't seem to get attention)

**Comment by mindashq** [comment]
This is fixed with the latest patch v1.8.3
